version: '3.3'
services:
  web-scraping-db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'web-scraping-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - web-scraping-db:/var/lib/mysql
volumes:
  web-scraping-db:
